spring:
  data:
    mongodb:
      uri:

config:
  rabbit:
    host: ""
    username: ""
    password: ""
    exchange: ""
    routing-key: ""
    queues:
      text-generator: ""
      default-queue: ""
  openai:
    token: ""
  replicateai:
    token: ""
    webhook: ""
    api_url: "https://api.replicate.com/v1/predictions"