spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ""
            client-secret: ""
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  data:
    mongodb:
      uri:

config:
  rabbit:
    host: "localhost"
    username: "guest"
    password: "guest"
    exchange: "amq.direct"
    routing-key: "description-generator-key"
    queues:
      text-generator: "text-generator"
      default-queue: "default-queue"
      image-generator: "image-generator"
  openai:
    token: ""
  replicateai:
    token: ""
    webhook: ""
    api_url: ""